using System;

namespace BongoCat.DJMAX.Common
{
    [Flags]
    public enum InputKeys
    {
        None = 0,

        Keyboard = 1 << 30,
        Controller = 1 << 31,

        #region Keyboard
        Left = 1 | Keyboard,
        Up = 2 | Keyboard,
        Right = 3 | Keyboard,
        Down = 4 | Keyboard,
        A = 5 | Keyboard,
        B = 6 | Keyboard,
        C = 7 | Keyboard,
        D = 8 | Keyboard,
        E = 9 | Keyboard,
        F = 10 | Keyboard,
        G = 11 | Keyboard,
        H = 12 | Keyboard,
        I = 13 | Keyboard,
        J = 14 | Keyboard,
        K = 15 | Keyboard,
        L = 16 | Keyboard,
        N = 17 | Keyboard,
        M = 18 | Keyboard,
        O = 19 | Keyboard,
        P = 20 | Keyboard,
        Q = 21 | Keyboard,
        R = 22 | Keyboard,
        S = 23 | Keyboard,
        T = 24 | Keyboard,
        U = 25 | Keyboard,
        V = 26 | Keyboard,
        W = 27 | Keyboard,
        X = 28 | Keyboard,
        Y = 29 | Keyboard,
        Z = 30 | Keyboard,
        D1 = 31 | Keyboard,
        D2 = 32 | Keyboard,
        D3 = 33 | Keyboard,
        D4 = 34 | Keyboard,
        D5 = 35 | Keyboard,
        D6 = 36 | Keyboard,
        D7 = 37 | Keyboard,
        D8 = 38 | Keyboard,
        D9 = 39 | Keyboard,
        D0 = 40 | Keyboard,
        DMinus = 41 | Keyboard,
        DPlus = 42 | Keyboard,
        NumLock = 43 | Keyboard,
        NumSlash = 44 | Keyboard,
        NumMultiply = 45 | Keyboard,
        NumMinus = 46 | Keyboard,
        NumPlus = 47 | Keyboard,
        NumPeriod = 48 | Keyboard,
        Num1 = 49 | Keyboard,
        Num2 = 50 | Keyboard,
        Num3 = 51 | Keyboard,
        Num4 = 52 | Keyboard,
        Num5 = 53 | Keyboard,
        Num6 = 54 | Keyboard,
        Num7 = 55 | Keyboard,
        Num8 = 56 | Keyboard,
        Num9 = 57 | Keyboard,
        Num0 = 58 | Keyboard,
        ScrollLock = 59 | Keyboard,
        OpenBrackets = 60 | Keyboard,
        CloseBrackets = 61 | Keyboard,
        Slash = 62 | Keyboard,
        BackSlash = 63 | Keyboard,
        Semicolon = 64 | Keyboard,
        Quote = 65 | Keyboard,
        BackQuote = 66 | Keyboard,
        Comma = 67 | Keyboard,
        Period = 68 | Keyboard,
        Space = 69 | Keyboard,
        BackSpace = 70 | Keyboard,
        Tab = 71 | Keyboard,
        CapsLock = 72 | Keyboard,
        LShift = 73 | Keyboard,
        RShift = 74 | Keyboard,
        LControl = 75 | Keyboard,
        LWindow = 76 | Keyboard,
        RWindow = 77 | Keyboard,
        LAlt = 78 | Keyboard,
        RAlt = 79 | Keyboard,
        Escape = 80 | Keyboard
        #endregion
    }
}
